services:
  api:
    restart: always
    image: romo1o/back-end-mse:latest
    container_name: api
    ports:
      - 5000:5000

  ui:
    restart: always
    image: romo1o/front-end-mse:latest
    container_name: ui
    ports:
      - 444:8501

  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/rmule/MLOPS_project/MachLeData-Project/postgres/data