name: Build and Publish docker Inference

on:
  push:
    paths:
      - 'model/**'  # only trigger if something in this folder changes
    branches:
      - main  # or your default branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./model
          file: ./model/Dockerfile
          push: true
          tags: romo1o/modelmse:latest
